Repository mubashir72/Hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#2 Duplicate Zero Problem Solved
  Java/Duplicate_Zero_Array_Problem/.idea/.gitignore
  Java/Duplicate_Zero_Array_Problem/.idea/.name
  Java/Duplicate_Zero_Array_Problem/.idea/description.html
  Java/Duplicate_Zero_Array_Problem/.idea/encodings.xml
  Java/Duplicate_Zero_Array_Problem/.idea/misc.xml
  Java/Duplicate_Zero_Array_Problem/.idea/modules.xml
  Java/Duplicate_Zero_Array_Problem/.idea/project-template.xml
  Java/Duplicate_Zero_Array_Problem/.idea/runConfigurations.xml
  Java/Duplicate_Zero_Array_Problem/Duplicate_Zero_Array_Problem.iml
  Java/Duplicate_Zero_Array_Problem/out/production/Duplicate_Zero_Array_Problem/com/company/Main.class
  Java/Duplicate_Zero_Array_Problem/src/com/company/Main.java
Labels: hactoberfest-accepted

#7 updated contributing.md
  CONTRIBUTING.MD
Labels: hacktoberfest, hacktoberfest-accepted

#8 updated the readme file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 Added Footer with copyright mark
  index.html
  styles.css
Labels: hacktoberfest-accepted
